# Generated by Django 2.2 on 2020-02-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200226_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
