# Generated by Django 2.2 on 2020-02-27 22:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200227_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trail',
        ),
    ]
