# Generated by Django 2.2 on 2020-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
